# Generated by Django 4.1 on 2022-08-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appUpload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=20)),
                ('title2', models.CharField(max_length=20)),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('image1', models.ImageField(upload_to='img')),
                ('image2', models.ImageField(upload_to='img')),
                ('image3', models.ImageField(upload_to='img')),
                ('content', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=20)),
                ('installation', models.CharField(max_length=500)),
                ('dimensions', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='Draft', max_length=10)),
            ],
        ),
    ]
